#!/bin/bash

# Copyright (C) 2014 Cheli Pineda Ferrer <cheli@aradaen.com>
#
# http://cheli.aradaen.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

BACKUP_PATH=""
LOG_PATH=""
DATABASES=""
DATE=`date +%G-%m-%d_%H.%M`
HOST=""
PORT=5432
USER=
RECIPIENT=

for DATABASE in $DATABASES
do

  FILE_NAME=$DATABASE-$DATE.dmp

  pg_dump -U $USER -h $HOST -p $PORT -F c -b -v -f /tmp/$FILE_NAME $DATABASE > $LOG_PATH/$DATABASE-$DATE.log 2> $LOG_PATH/error-$DATABASE-$DATE.log
  bzip2 /tmp/$FILE_NAME

  if [ $RECIPIENT ]; then

    gpg --output $BACKUP_PATH/$FILE_NAME.bz2.gpg --encrypt --recipient $RECIPIENT /tmp/$FILE_NAME.bz2
    rm /tmp/$FILE_NAME.bz2

  else

    mv /tmp/$FILE_NAME.bz2 $BACKUP_PATH

  fi

done;

